import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  orb: {
    position: 'absolute',
    borderRadius: 999,
    opacity: 0.95,
  },
  orbPrimary: {
    width: 340,
    height: 340,
    top: -120,
    right: -60,
    backgroundColor: 'rgba(14, 165, 233, 0.20)',
  },
  orbWarm: {
    width: 280,
    height: 280,
    bottom: 40,
    left: -80,
    backgroundColor: 'rgba(245, 158, 11, 0.14)',
  },
  orbSoft: {
    width: 220,
    height: 220,
    top: '38%',
    left: '45%',
    backgroundColor: 'rgba(59, 130, 246, 0.08)',
  },
  authShell: {
    flex: 1,
    width: '100%',
    alignSelf: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 32,
    gap: 18,
    maxWidth: 1160,
  },
  authShellDesktop: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  authHero: {
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
    backgroundColor: 'rgba(15, 23, 42, 0.92)',
    padding: 24,
    gap: 16,
  },
  authHeroDesktop: {
    flex: 1.1,
    minHeight: 520,
    justifyContent: 'center',
  },
  authHeroContent: {
    gap: 10,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: 'rgba(14, 165, 233, 0.14)',
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  heroBadgeText: {
    color: '#dbeafe',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
    fontFamily: 'Sarabun_700Bold',
  },
  authBrand: {
    color: '#f8fafc',
    fontSize: 72,
    lineHeight: 72,
    letterSpacing: -1.8,
    fontFamily: 'Sarabun_700Bold',
  },
  authTitle: {
    color: '#cbd5e1',
    fontSize: 24,
    lineHeight: 31,
    fontFamily: 'Sarabun_700Bold',
    maxWidth: 520,
  },
  authCopy: {
    color: '#cbd5e1',
    fontSize: 15,
    lineHeight: 23,
    maxWidth: 500,
    fontFamily: 'Sarabun_400Regular',
  },
  authHeroDivider: {
    width: 72,
    height: 1,
    backgroundColor: 'rgba(148, 163, 184, 0.36)',
  },
  authHeroFootnote: {
    gap: 6,
    maxWidth: 460,
  },
  authHeroFootnoteTitle: {
    color: '#f8fafc',
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Sarabun_700Bold',
  },
  authHeroFootnoteCopy: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 21,
    fontFamily: 'Sarabun_400Regular',
  },
  authCard: {
    borderRadius: 30,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.22)',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    padding: 24,
    gap: 16,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.08,
    shadowRadius: 32,
    elevation: 6,
  },
  authCardDesktop: {
    flex: 0.9,
    justifyContent: 'center',
    minHeight: 520,
  },
  authCardHeader: {
    minHeight: 122,
    gap: 6,
  },
  authModeSwitch: {
    flexDirection: 'row',
    borderRadius: 18,
    backgroundColor: '#e2e8f0',
    padding: 4,
    gap: 6,
  },
  authModePill: {
    flex: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  authModePillActive: {
    backgroundColor: '#ffffff',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 2,
  },
  authModeText: {
    color: '#475569',
    fontSize: 13,
    fontWeight: '700',
    fontFamily: 'Sarabun_700Bold',
  },
  authModeTextActive: {
    color: '#0f172a',
  },
  authEyebrow: {
    color: '#0369a1',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    fontFamily: 'Sarabun_700Bold',
  },
  authCardTitle: {
    color: '#0f172a',
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
    fontFamily: 'Sarabun_700Bold',
  },
  authCardCopy: {
    color: '#475569',
    fontSize: 14,
    lineHeight: 21,
    fontFamily: 'Sarabun_400Regular',
  },
  authFieldGroup: {
    gap: 8,
  },
  authFormFields: {
    gap: 14,
  },
  authAnimatedField: {
    overflow: 'hidden',
  },
  authFieldHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  authFieldLabel: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '700',
    fontFamily: 'Sarabun_700Bold',
  },
  authFieldHint: {
    color: '#64748b',
    fontSize: 12,
    fontFamily: 'Sarabun_400Regular',
  },
  authInput: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: '#0f172a',
    fontFamily: 'Sarabun_400Regular',
  },
  passwordStrengthCard: {
    borderRadius: 18,
    backgroundColor: '#f8fafc',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  passwordStrengthHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  passwordStrengthLabel: {
    color: '#334155',
    fontSize: 13,
    fontFamily: 'Sarabun_600SemiBold',
  },
  passwordStrengthBadge: {
    fontSize: 13,
    fontFamily: 'Sarabun_700Bold',
  },
  passwordStrengthTrack: {
    flexDirection: 'row',
    gap: 6,
  },
  passwordStrengthSegment: {
    flex: 1,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#e2e8f0',
    overflow: 'hidden',
  },
  passwordStrengthSegmentFill: {
    width: '100%',
    height: '100%',
    borderRadius: 999,
  },
  passwordStrengthChecklist: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  passwordStrengthItemCard: {
    width: '48%',
  },
  passwordStrengthItem: {
    color: '#64748b',
    fontSize: 12,
    lineHeight: 18,
    fontFamily: 'Sarabun_400Regular',
  },
  passwordStrengthItemPass: {
    color: '#166534',
    fontFamily: 'Sarabun_600SemiBold',
  },
  authErrorBox: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#fecaca',
    backgroundColor: '#fef2f2',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  authErrorText: {
    color: '#b91c1c',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
    fontFamily: 'Sarabun_600SemiBold',
  },
  authSubmitShell: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 18,
  },
  authSubmitGlow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 18,
    backgroundColor: '#1d4ed8',
  },
  authSubmitBeam: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 120,
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
  },
  primaryButton: {
    alignItems: 'center',
    borderRadius: 18,
    backgroundColor: '#0f172a',
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  primaryButtonDisabled: {
    backgroundColor: '#94a3b8',
  },
  primaryButtonText: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '700',
    fontFamily: 'Sarabun_700Bold',
  },
  authSubmitContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  authSwitchLink: {
    alignItems: 'center',
    paddingVertical: 6,
  },
  authSwitchLinkText: {
    color: '#0369a1',
    fontSize: 13,
    fontWeight: '700',
    fontFamily: 'Sarabun_700Bold',
  },
  scrollShell: {
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 36,
    gap: 12,
  },
  dashboardShell: {
    flex: 1,
    position: 'relative',
  },
  topBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  topBarLayer: {
    zIndex: 30,
  },
  topBarMeta: {
    gap: 4,
    flexShrink: 1,
  },
  topBarTitle: {
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontFamily: 'Sarabun_700Bold',
  },
  topBarCopy: {
    color: '#475569',
    fontSize: 13,
    fontFamily: 'Sarabun_400Regular',
  },
  topBarActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  profileMenuShell: {
    position: 'relative',
    minWidth: 240,
    alignItems: 'flex-end',
    zIndex: 40,
  },
  profileMenuButton: {
    minWidth: 240,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.24)',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: 10,
    paddingVertical: 10,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 2,
  },
  profileMenuButtonActive: {
    borderColor: 'rgba(14, 165, 233, 0.36)',
    backgroundColor: '#ffffff',
  },
  profileMenuButtonPressed: {
    borderColor: 'rgba(14, 165, 233, 0.42)',
    backgroundColor: '#f0f9ff',
    transform: [{ scale: 0.985 }],
  },
  profileAvatar: {
    width: 42,
    height: 42,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f172a',
  },
  profileAvatarText: {
    color: '#f8fafc',
    fontSize: 15,
    fontFamily: 'Sarabun_700Bold',
  },
  profileMenuButtonMeta: {
    flex: 1,
    gap: 1,
  },
  profileMenuButtonName: {
    color: '#0f172a',
    fontSize: 15,
    fontFamily: 'Sarabun_700Bold',
  },
  profileMenuButtonHint: {
    color: '#64748b',
    fontSize: 12,
    fontFamily: 'Sarabun_400Regular',
  },
  profileMenuCaret: {
    color: '#475569',
    fontSize: 13,
    fontFamily: 'Sarabun_700Bold',
  },
  profileMenuCard: {
    width: 290,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.22)',
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    padding: 12,
    gap: 8,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.12,
    shadowRadius: 30,
    elevation: 6,
    zIndex: 20,
  },
  profileMenuModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.04)',
  },
  profileMenuModalRoot: {
    flex: 1,
  },
  profileMenuBlurLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  profileMenuShadeLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(248, 250, 252, 0.18)',
  },
  profileMenuCloseLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  profileMenuModalShell: {
    position: 'absolute',
    width: 290,
    zIndex: 20,
  },
  profileMenuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 20,
    backgroundColor: '#f8fafc',
    padding: 12,
  },
  profileAvatarLarge: {
    width: 50,
    height: 50,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f172a',
  },
  profileAvatarLargeText: {
    color: '#f8fafc',
    fontSize: 18,
    fontFamily: 'Sarabun_700Bold',
  },
  profileMenuHeaderMeta: {
    flex: 1,
    gap: 2,
  },
  profileMenuName: {
    color: '#0f172a',
    fontSize: 15,
    fontFamily: 'Sarabun_700Bold',
  },
  profileMenuEmail: {
    color: '#64748b',
    fontSize: 12,
    fontFamily: 'Sarabun_400Regular',
  },
  profileMenuItem: {
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 11,
    gap: 2,
  },
  profileMenuItemActive: {
    backgroundColor: '#eff6ff',
  },
  profileMenuItemHover: {
    backgroundColor: '#f8fafc',
  },
  profileMenuItemPressed: {
    backgroundColor: '#e0f2fe',
    transform: [{ scale: 0.988 }],
  },
  profileMenuItemText: {
    color: '#0f172a',
    fontSize: 14,
    fontFamily: 'Sarabun_700Bold',
  },
  profileMenuItemTextActive: {
    color: '#075985',
  },
  profileMenuItemHint: {
    color: '#64748b',
    fontSize: 12,
    fontFamily: 'Sarabun_400Regular',
  },
  profileMenuDivider: {
    height: 1,
    backgroundColor: '#e2e8f0',
    marginVertical: 2,
  },
  profileMenuDangerItem: {
    borderRadius: 18,
    backgroundColor: '#fff1f2',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  profileMenuDangerItemHover: {
    backgroundColor: '#ffe4e6',
  },
  profileMenuDangerItemPressed: {
    backgroundColor: '#ffe4e6',
    transform: [{ scale: 0.988 }],
  },
  profileMenuDangerText: {
    color: '#be123c',
    fontSize: 14,
    fontFamily: 'Sarabun_700Bold',
  },
  routeLoadingModalRoot: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  routeLoadingBlurLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  routeLoadingShadeLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(241, 245, 249, 0.34)',
  },
  routeLoadingCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.24)',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    paddingHorizontal: 22,
    paddingVertical: 20,
    alignItems: 'center',
    gap: 12,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.12,
    shadowRadius: 30,
    elevation: 8,
  },
  routeLoadingDots: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  routeLoadingDot: {
    width: 12,
    height: 12,
    borderRadius: 999,
  },
  routeLoadingDotPrimary: {
    backgroundColor: '#0ea5e9',
  },
  routeLoadingDotSoft: {
    backgroundColor: '#38bdf8',
  },
  routeLoadingDotWarm: {
    backgroundColor: '#f59e0b',
  },
  routeLoadingTitle: {
    color: '#0f172a',
    fontSize: 24,
    lineHeight: 29,
    textAlign: 'center',
    fontFamily: 'Sarabun_700Bold',
  },
  routeLoadingCopy: {
    color: '#64748b',
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    fontFamily: 'Sarabun_400Regular',
  },
  logoutModalRoot: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  logoutModalBlurLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  logoutModalShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.10)',
  },
  logoutModalCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.24)',
    backgroundColor: 'rgba(255, 255, 255, 0.94)',
    padding: 20,
    gap: 16,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.14,
    shadowRadius: 30,
    elevation: 8,
  },
  logoutModalBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#eff6ff',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  logoutModalBadgeText: {
    color: '#075985',
    fontSize: 12,
    fontFamily: 'Sarabun_700Bold',
  },
  logoutModalBody: {
    gap: 6,
  },
  logoutModalTitle: {
    color: '#0f172a',
    fontSize: 26,
    lineHeight: 31,
    fontFamily: 'Sarabun_700Bold',
  },
  logoutModalCopy: {
    color: '#475569',
    fontSize: 14,
    lineHeight: 21,
    fontFamily: 'Sarabun_400Regular',
  },
  logoutModalActions: {
    flexDirection: 'row',
    gap: 10,
  },
  logoutModalGhostButton: {
    flex: 1,
    alignItems: 'center',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  logoutModalGhostButtonPressed: {
    borderColor: '#94a3b8',
    backgroundColor: '#f8fafc',
    transform: [{ scale: 0.988 }],
  },
  logoutModalGhostText: {
    color: '#334155',
    fontSize: 15,
    fontFamily: 'Sarabun_700Bold',
  },
  logoutModalDangerButton: {
    flex: 1,
    alignItems: 'center',
    borderRadius: 18,
    backgroundColor: '#0f172a',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  logoutModalDangerButtonPressed: {
    backgroundColor: '#1e293b',
    transform: [{ scale: 0.988 }],
  },
  logoutModalDangerText: {
    color: '#f8fafc',
    fontSize: 15,
    fontFamily: 'Sarabun_700Bold',
  },
  desktopLocationCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.24)',
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    padding: 20,
    gap: 14,
  },
  desktopLocationEyebrow: {
    color: '#0369a1',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  desktopLocationTitle: {
    color: '#0f172a',
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '800',
    fontFamily: 'Sarabun_700Bold',
  },
  desktopLocationCopy: {
    color: '#475569',
    fontSize: 14,
    lineHeight: 21,
    fontFamily: 'Sarabun_400Regular',
  },
  desktopLocationStat: {
    borderRadius: 20,
    backgroundColor: '#f8fafc',
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 6,
  },
  desktopLocationStatLabel: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    fontFamily: 'Sarabun_700Bold',
  },
  desktopLocationStatValue: {
    color: '#0f172a',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
    fontFamily: 'Sarabun_600SemiBold',
  },
  desktopGrid: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  desktopCol: {
    flex: 1,
    gap: 12,
  },
  skeletonShell: {
    flex: 1,
    width: '100%',
    maxWidth: 1160,
    alignSelf: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 32,
    gap: 18,
  },
  skeletonHero: {
    borderRadius: 30,
    backgroundColor: 'rgba(15, 23, 42, 0.18)',
    padding: 24,
    gap: 14,
  },
  skeletonCard: {
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    padding: 24,
    gap: 14,
  },
  skeletonBlock: {
    borderRadius: 18,
    backgroundColor: 'rgba(148, 163, 184, 0.35)',
  },
  skeletonBadge: {
    width: 140,
    height: 28,
  },
  skeletonTitlePrimary: {
    width: '88%',
    height: 38,
  },
  skeletonTitleSecondary: {
    width: '72%',
    height: 38,
  },
  skeletonCopy: {
    width: '100%',
    height: 18,
  },
  skeletonCopyShort: {
    width: '78%',
    height: 18,
  },
  skeletonMetricRow: {
    flexDirection: 'row',
    gap: 10,
  },
  skeletonMetricCard: {
    flex: 1,
    height: 72,
  },
  skeletonModeSwitch: {
    width: '100%',
    height: 46,
  },
  skeletonFormTitle: {
    width: '62%',
    height: 32,
  },
  skeletonInput: {
    width: '100%',
    height: 52,
  },
  skeletonButton: {
    width: '100%',
    height: 54,
  },
  skeletonLink: {
    width: '58%',
    height: 20,
    alignSelf: 'center',
  },
});
